package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2013-07-24T13:57:13.117+08:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "ServiceBeanService", 
                  wsdlLocation = "http://localhost:8080/WebServiceTest/ServiceBean?wsdl",
                  targetNamespace = "http://webservice/") 
public class ServiceBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "ServiceBeanService");
    public final static QName ServiceBeanPort = new QName("http://webservice/", "ServiceBeanPort");
    
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/WebServiceTest/ServiceBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceBeanService.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}", "http://localhost:8080/WebServiceTest/ServiceBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServiceBean
     */
    @WebEndpoint(name = "ServiceBeanPort")
    public ServiceBean getServiceBeanPort() {
        return super.getPort(ServiceBeanPort, ServiceBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceBean
     */
    @WebEndpoint(name = "ServiceBeanPort")
    public ServiceBean getServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(ServiceBeanPort, ServiceBean.class, features);
    }

}
